'use client';

export default function UserAgreementEnPage() {
  return (
    <div className="prose prose-sm sm:prose-base lg:prose-lg xl:prose-2xl m-auto p-4 sm:p-6 lg:p-8 w-4/5">
      <h1 className="text-2xl font-bold my-4 text-center">User Agreement</h1>
      <div className="flex flex-col gap-2 my-4 text-center">
        <p className="text-sm text-gray-500">
          <strong>Last Updated:</strong> June 15, 2025
        </p>
        <p className="text-sm text-gray-500">
          <strong>Effective Date:</strong> May 22, 2025
        </p>
      </div>
      <div className="flex flex-col gap-2 my-4">
        <p>
          This User Agreement ("Agreement") is a binding legal contract between
          you ("User," "you," or "your") and Turbo AI Technology (Shanghai) Co.,
          Ltd. ("Turbo AI," "we," "us," or "our"). This Agreement governs your
          access to and use of the website www.iturboai.com (the "Site") and all
          related software, applications, components, templates, and services
          (collectively, the "Services").
        </p>
        <p>
          By creating an account, making a purchase, or using the Services, you
          acknowledge that you have read, understood, and agree to be bound by
          this Agreement, our{' '}
          <a href="/privacy" className="text-primary underline">
            Privacy Policy
          </a>
          , and our{' '}
          <a href="/term" className="text-primary underline">
            Terms & Conditions
          </a>
          , which are incorporated herein by reference.
        </p>
        <h2 className="text-lg font-bold my-2">1. User Accounts</h2>
        <p>
          <strong>1.1. Registration:</strong> To access certain features of the
          Services, you must register for an account. You agree to provide
          accurate, current, and complete information during the registration
          process and to update such information to keep it accurate, current,
          and complete.
        </p>
        <p>
          <strong>1.2. Eligibility:</strong> You must be at least 18 years old
          to use our Services. By creating an account, you represent and warrant
          that you meet this requirement.
        </p>
        <p>
          <strong>1.3. Account Security:</strong> You are responsible for
          safeguarding your password and for all activities that occur under
          your account. You agree to notify us immediately of any unauthorized
          use of your account.
        </p>
        <h2 className="text-lg font-bold my-2">2. Grant of License</h2>
        <p>
          Subject to your compliance with this Agreement and payment of any
          applicable fees, Turbo AI grants you a limited, non-exclusive,
          non-transferable, non-sublicensable license to access and use the
          Services according to the terms of your selected plan (e.g., Solo,
          Startup, Organization), as detailed in our Terms & Conditions.
        </p>
        <h2 className="text-lg font-bold my-2">
          3. User Content and AI Output
        </h2>
        <p>
          <strong>3.1. Your Content:</strong> You retain all ownership rights to
          the text, files, and other information you provide to the Services
          ("Input").
        </p>
        <p>
          <strong>3.2. AI-Generated Content:</strong> Subject to your compliance
          with this Agreement, Turbo AI assigns to you all its rights, title,
          and interest in and to the content generated by the Services based on
          your Input ("Output").
        </p>
        <p>
          <strong>3.3. Our Use of Content:</strong> You grant us a worldwide,
          non-exclusive, royalty-free license to use your Input and Output to
          provide, maintain, and improve the Services and to develop new
          products. This data will be handled in accordance with our Privacy
          Policy.
        </p>
        <p>
          <strong>3.4. Responsibility:</strong> You are solely responsible for
          your Input and for your use of the Output. You represent and warrant
          that your Input does not infringe on any third-party rights and that
          your use of the Output will comply with all applicable laws. Due to
          the nature of AI, the Output may not be unique, and we provide no
          warranty regarding its originality.
        </p>
        <h2 className="text-lg font-bold my-2">4. Acceptable Use Policy</h2>
        <p>You agree not to use the Services to:</p>
        <ul className="list-disc list-inside pl-4 gap-2">
          <li>Engage in any illegal, fraudulent, or abusive activities.</li>
          <li>Infringe on the intellectual property rights of others.</li>
          <li>
            Generate content that is hateful, harassing, violent, or
            pornographic.
          </li>
          <li>
            Reverse-engineer, decompile, or otherwise attempt to discover the
            source code of the Services.
          </li>
          <li>
            Use web scraping, bots, or other automated means to access the
            Services for any purpose without our express written permission.
          </li>
          <li>Resell or sublicense the Services without authorization.</li>
        </ul>
        <h2 className="text-lg font-bold my-2">
          5. Fees, Payment, and Refunds
        </h2>
        <p>
          All fees, payment terms, and refund policies are governed by our Terms
          & Conditions. By making a purchase, you agree to these terms.
        </p>
        <h2 className="text-lg font-bold my-2">6. Intellectual Property</h2>
        <p>
          Excluding your Input and Output, all content, features, and
          functionality of the Site and Services, including but not limited to
          all software, text, displays, images, video, and audio, and the
          design, selection, and arrangement thereof, are owned by Turbo AI, its
          licensors, or other providers of such material and are protected by -
          international copyright, trademark, and other intellectual property
          laws.
        </p>
        <h2 className="text-lg font-bold my-2">7. Termination</h2>
        <p>
          We may terminate or suspend your account and access to the Services
          immediately, without prior notice or liability, for any reason
          whatsoever, including without limitation if you breach this Agreement.
          Upon termination, your right to use the Services will immediately
          cease.
        </p>
        <h2 className="text-lg font-bold my-2">
          8. Disclaimers and Limitation of Liability
        </h2>
        <p>
          The Services are provided "AS IS" without warranties of any kind. Our
          liability to you for any cause whatsoever, and regardless of the form
          of the action, will at all times be limited to the amount paid, if
          any, by you to us during the six (6) month period prior to any cause
          of action arising. Please review our full Disclaimer for more details.
        </p>
        <h2 className="text-lg font-bold my-2">9. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless Turbo AI and its
          licensees and licensors, and their employees, contractors, agents,
          officers, and directors, from and against any and all claims, damages,
          obligations, losses, liabilities, costs or debt, and expenses
          (including but not limited to attorney's fees), resulting from or
          arising out of your use and access of the Service, or a breach of this
          Agreement.
        </p>
        <h2 className="text-lg font-bold my-2">10. Governing Law</h2>
        <p>
          This Agreement shall be governed by the laws of the jurisdiction where
          Turbo AI Technology (Shanghai) Co., Ltd. is registered, without regard
          to its conflict of law provisions.
        </p>
        <h2 className="text-lg font-bold my-2">11. Changes to the Agreement</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace
          this Agreement at any time. We will provide reasonable notice of any
          changes by posting the new Agreement on the Site. Your continued use
          of the Services after any such changes constitutes your acceptance of
          the new Agreement.
        </p>
        <h2 className="text-lg font-bold my-2">12. Contact Information</h2>
        <p>
          If you have any questions about this Agreement, please contact us at{' '}
          <a href="mailto:turboai@gmail.com" className="text-primary underline">
            turboai@gmail.com
          </a>
          .
        </p>
      </div>
    </div>
  );
}
